name: Auto-build for browser

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
    - uses: pnpm/action-setup@v2
      with:
        version: 8.5.1
    - name: Install
      run: pnpm i
    - run: node build-browser
    - name: Create and publish release
      run: | 
        buildName=$(date "+%Y%m%d%H%M%S")
        gh release create $buildName
        gh release upload $buildName dist/TekstowoAPI-browser.js
        gh release edit build --title $buildName
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
